name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Check out code
        uses: actions/checkout@v1
      - name: cache go mod
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.48.0
          export PATH=$PATH:$(go env GOPATH)/bin
          make check
          make build
      - name: Test
        run: |
          export NYDUS_VERSION=v2.0.1
          curl -L https://github.com/dragonflyoss/image-service/releases/download/$NYDUS_VERSION/nydus-static-$NYDUS_VERSION-linux-amd64.tgz > nydus-static-$NYDUS_VERSION-linux-amd64.tgz
          tar xzvf nydus-static-$NYDUS_VERSION-linux-amd64.tgz
          sudo mv nydus-static/nydusd-fusedev /usr/bin/nydusd
          sudo mv nydus-static/nydusify /usr/bin/nydusify
          sudo mv nydus-static/nydus-image /usr/bin/nydus-image
          sudo podman run -d -it -p 5000:5000 --name registry docker.io/library/registry:2
          sudo nydusify convert --source ubuntu --target localhost:5000/ubuntu:latest-nydus
          sudo mkdir -p /var/lib/nydus-store
          sudo cp misc/nydus-config.json /etc/nydusd-config.json
          sudo cp misc/storage.conf /etc/containers/storage.conf
          nohup sudo bin/nydus-store --log-to-stdout --log-level debug --config-path /etc/nydusd-config.json --root /var/lib/nydus-store &
          sudo podman run -it --tls-verify=false --rm localhost:5000/ubuntu:latest-nydus echo hello word
